markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://ChuGiFtedScholAr
author: ChuGiFtedScholAr
highlighter: pygments
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16
