# Site specific settings
title: "hello"
name: "ChuGiFtedScholAr"
keywords: "ChuGiFtedScholAr"
baseurl: "/darcli"
url: "https://ChuGiFtedScholAr.github.io"
description: "心间纵有万千语，却做桥头染别离"
cover: "/assets/img/favicon.png"
fanpage_id: ""

# Site general settings
lang: "zh"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
