# Site settings ...
uri: ChuGiFtedScholAr.github.io
url: https://ChuGiFtedScholAr.github.io
name: ChuGiFtedScholAr
title: ChuGiFtedScholAr
email: chu.overthink@gmail.com
author: ChuGiFtedScholAr
baseurl: ""
keywords: "ChuGiFtedScholAr"
description: "I'm ChuGiFtedScholAr , uh , Suddenly feeling good awkward words , Sex: Male , Hobby: Female , no idea , 人活着嘛 ，活着就好 , If you need my help ,Please e-mail , Certainly can not respond promptly ."


#social_username: ChuGiFtedScholAr
twitter_username: who_is_chu
github_username:  ChuGiFtedScholAr
# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
