# Site settings ...
uri: ChuGiFtedScholAr.github.io
url: https://ChuGiFtedScholAr.github.io
name: ChuGiFtedScholAr
title: ChuGiFtedScholAr
email: chu.overthink@gmail.com
author: ChuGiFtedScholAr
baseurl: ""
keywords: "ChuGiFtedScholAr"
description: "我是楚才子，呃，突然感觉这话好别扭，本人性别男爱好女，没什么追求啦，人活着吗，活着就好，如果有事情要我帮忙，请发邮件，肯定不能及时回复"
contact: "想撩我的尽管来，哈哈哈！  <br>
          xmpp：ChuGiFtedScholAr@jechat.com   <br>  
          tox ：ChuGiFtedScholAr@toxme.io  <br>
          bitmsg：BM-2cWTe2TwKSPfaoooBUDZ92W4XprkVY1MFi  <br>
          或者twitter上@我，私我也可以啦  <br>"

#social_username: ChuGiFtedScholAr
twitter_username: who_is_chu
github_username:  ChuGiFtedScholAr
# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
