# Site settings
title: "ChuGiFtedScholAr"
bye_message: "end ."
baseurl: "/"
url: "https://ChuGiFtedScholAr.github.io"
disqus: 

# Header settings
nick: "ChuGiFtedScholAr"
mail:
    domain: "protonmail"
    ext: "ch"
source_code: 
    server: "github.com"
    nick: "ChuGiFtedScholAr"
blog: 
    server: "wordpress.com"
    nick: ""
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
