markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: https://ChuGiFtedScholAr.github.io
author: ChuGiFtedScholAr
highlighter: pygments
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16
